name: runelite
base: core20
title: RuneLite
version: git
summary: A popular free, open-source and super fast client for Old School RuneScape
description: |
  A popular free, open-source and super fast client for Old School RuneScape

type: app
grade: stable
confinement: strict
icon: snap/gui/runelite.png
license: BSD-2-Clause

parts:
  adoptopenjdk:
    plugin: dump
    source: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jre_x64_linux_hotspot_11.0.8_10.tar.gz
    source-checksum: "sha256/98615b1b369509965a612232622d39b5cefe117d6189179cbad4dcef2ee2f4e1"
    stage-packages:
      - libxi6
      - libxrender1
      - libxtst6

  runelite:
    plugin: dump
    source-type: local
    source: target/
    stage-packages:
      - libglu1-mesa
      - libpulse0
      - libasound2
      - libasound2-plugins
    override-pull: |
      snapcraftctl pull
      find . -not -name 'RuneLite.jar' -delete
      if [ ! -f RuneLite.jar ]
      then
        echo "Run maven prior to running snapcraft!"
        exit 1
      fi

  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

apps:
  runelite:
    command: bin/java -jar $SNAP/RuneLite.jar
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - x11
      - opengl
      - pulseaudio

    extensions: [ gnome-3-38 ]
    environment:
      _JAVA_OPTIONS: -Duser.home="$SNAP_USER_COMMON"
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
